chore(): task #1005
SNKz0610/Android-FirstMonthExcercise pull request #1
Opened 2021-05-10 10:17 UTC by SNKz0610

Adding Android homework 10/05/2021 about first month ending by using git flow.Closes task #1005

2021-05-10 23:54 UTC, linhvnguyen9 commented
#1 Phần tạo nhánh theo Git flow b làm khá ok r, bao gồm cách tách nhánh (master, develop, feature,...), cách tạo pull request. Còn 1 góp ý nhỏ chỗ đặt tên nhánh `feature/feature_register`. Ở đây b đã ghi feature ở đằng trước r, vì thế b ko cần phải ghi feature ở phần sau dấu gạch nữa

2021-05-11 00:17 UTC, linhvnguyen9 requested changes
B check review, sửa code và push lên nhánh feature của b nhé!

2021-05-11 00:17 UTC, linhvnguyen9 commented on app/src/main/res/layout/activity_main.xml
> +        android:backgroundTint="#ffffff"
1 tip nhỏ cho b ở đây, nếu b muốn cái nút đó trong suốt (ko có viền với nền ở quanh), b có thể xài `android:background="@android:color/transparent"`

2021-05-11 00:17 UTC, linhvnguyen9 commented on app/src/main/res/layout/activity_main.xml
> +    <ImageButton
Ở đây b đang để phần bên trong của nút (icon và ảnh) dưới dạng 1 ảnh duy nhất. Điều gì xảy ra nếu app của bạn hỗ trợ 20 ngôn ngữ? Bạn sẽ phải sửa như thế nào để dịch hết dòng chữ chú thích cho từng nút kia?

2021-05-11 00:17 UTC, linhvnguyen9 commented on app/src/main/java/com/example/register/MainActivity.java
> +public class MainActivity extends AppCompatActivity {
Project của b đang code = Java, có thể b đang để mặc định ngôn ngữ là Java nên quên mất :)))))). Các part đằng sau của mình yêu cầu code = Kotlin, b thử tìm cách đổi, ít nhất là file MainActivity này sang Kotlin nhé!

2021-05-11 04:10 UTC, closed without merging

2021-05-11 04:11 UTC, SNKz0610 commented
Fixing something belong to the comment